### ISSUE TITLE
CircuitBreaker reset function not reset scheduler when automaticTransitionToHalfOpen enabled

### ISSUE THREAD

**Issue by SeliMeli** [resilience4j/resilience4j#1039]
Resilience4j version: 1.3.1

Java version: 1.8

When using reset state from Open to Close, the scheduled auto transition job still there. So when state transition from Close to Open again (normally), the state machine will automatically transit to half open before given wait time arrive. And if it dose not in open state and auto transition triggered, an exception will be thrown which may lead confuse.

Found the auto transition job scheduled at Open state's constructor and never been canceled after reset.

**Comment by dlsrb6342** [comment]
Hi @SeliMeli 
This bug is duplicated with #991 . And it is fixed. Please use 1.5.0 version.

**Comment by RobWin** [comment]
I think it as fixed with 1.5.0

**Comment by woncho3** [comment]
Hi, I guess this one still exists on the latest 1.7.0

Resilience4j version: 1.7.0

Java version: 1.11

	@Test
	public void testResetAndHook() throws InterruptedException {
		CircuitBreakerConfig config = CircuitBreakerConfig.custom()
				.waitDurationInOpenState(Duration.ofSeconds(2))
				.automaticTransitionFromOpenToHalfOpenEnabled(true)
				.maxWaitDurationInHalfOpenState(Duration.ofSeconds(2))
				.build();
		// A state will be toggled between open & half_open every 2 seconds
		// once a circuit breaker goes into open or half_open state

		CircuitBreaker cb = CircuitBreaker.of("test", config);
		cb.getEventPublisher().onEvent(e -> System.out.println(e.toString()));  // logging for event

		cb.transitionToOpenState();   // 1. force transition: closed -> open
		Thread.sleep(7000);           // 2. auto transition: open -> half_open -> open -> half_open
		cb.reset();                   // 3. reset: half_open -> closed
		Thread.sleep(10000);          // 4. auto transition (keep working): closed -> open -> half_open ...
	}

Execution Result:

	2021-04-07T15:09:42.813218+09:00[Asia/Seoul]: CircuitBreaker 'test' changed state from CLOSED to OPEN
	2021-04-07T15:09:44.818271+09:00[Asia/Seoul]: CircuitBreaker 'test' changed state from OPEN to HALF_OPEN
	2021-04-07T15:09:46.818332+09:00[Asia/Seoul]: CircuitBreaker 'test' changed state from HALF_OPEN to OPEN
	2021-04-07T15:09:48.818714+09:00[Asia/Seoul]: CircuitBreaker 'test' changed state from OPEN to HALF_OPEN
	2021-04-07T15:09:49.815185+09:00[Asia/Seoul]: CircuitBreaker 'test' changed state from HALF_OPEN to CLOSED
	2021-04-07T15:09:49.816993+09:00[Asia/Seoul]: CircuitBreaker 'test' reset
	2021-04-07T15:09:50.818985+09:00[Asia/Seoul]: CircuitBreaker 'test' changed state from CLOSED to OPEN
	2021-04-07T15:09:52.819346+09:00[Asia/Seoul]: CircuitBreaker 'test' changed state from OPEN to HALF_OPEN
	2021-04-07T15:09:54.819674+09:00[Asia/Seoul]: CircuitBreaker 'test' changed state from HALF_OPEN to OPEN
	2021-04-07T15:09:56.820028+09:00[Asia/Seoul]: CircuitBreaker 'test' changed state from OPEN to HALF_OPEN
	2021-04-07T15:09:58.820150+09:00[Asia/Seoul]: CircuitBreaker 'test' changed state from HALF_OPEN to OPEN

As I look into the code, it seems call for `preTransitionHook()` is missing on `reset()` implementation.
